overview:
  title: Point Of Interest
  image: logo.png
  description: Shows how a product detail page could look with 360° images and points of interest used.
  order: 4
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      highlight: DEAL OF THE DAY
      footer:
        credits:
          photos:
            - author: 360ties GmbH
          viewer:
            link: https://www.neptunelabs.com/fsi-showcase/
      fsi:
        viewer: true
        touchZoom: true
        thumbBar: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "poi.css"
    js: "poi.js"
jsfiddle:
  deploy: true
