overview:
  title: Product Detail Page
  image: logo.png
  description: This sample shows a simple showcase embedded in a product page.
  order: 6
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      highlight: DEAL OF THE DAY
      footer:
        credits:
          photos:
            - author: NeptuneLabs GmbH
          viewer:
            link: https://www.neptunelabs.com/fsi-showcase/
      fsi:
        viewer: true
        touchZoom: true
        thumbBar: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    js: "pdp.js"
    css: "pdp.css"
jsfiddle:
  deploy: true
