overview:
  title: Photographer Portfolio
  image: logo.png
  description: Shows how a portfolio could be displayed with ImageGrid and Metadata used and a zoom viewer on top.
  priority: 5
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      footer:
        credits:
          photos:
            - author: Samuel Ferrara
              link: https://unsplash.com/@samferrara?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
              platform: Unsplash
          viewer:
            link: https://www.neptunelabs.com/fsi-showcase/
      fsi:
        viewer: true
        imageGrid: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "portfolio.css"
    js: "portfolio.js"
jsfiddle:
  deploy: true
