overview:
  title: Photographer Portfolio
  image: logo.png
  description: Shows how a portfolio with ImageGrid and Metadata plus a zoom viewer on top looks.
  facts:
    - Showcase collection
    - With FSI ImageGrid
    - Use of meta data
  priority: 5
schema: bootstrap-taupe
sample:
  menu:
    data: misc-menu.yml
  footer:
    credits:
      photos:
        - author: Samuel Ferrara
          link: https://unsplash.com/@samferrara?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText
          platform: Unsplash
      viewer:
        link: https://www.neptunelabs.com/fsi-showcase/
  fsi:
    viewer: true
    imageGrid: true
  bootstrap:
    icons: true
